spring:
  datasource:
    username: owner_service
    password: password
    url: jdbc:mysql://localhost:3306/ownerservice?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC

# Enable logging for config troubleshooting
logging:
  level:
    org.hibernate.SQL: DEBUG
    com.zaxxer.hikari.HikariConfig: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE