spring:
  datasource:
    username: owner_service
    password: password
    url: jdbc:mysql://db:3306/ownerservice?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
  #Zipkin
  zipkin:
    enabled: true
    baseUrl: http://zipkin:9411/
# Enable logging for config troubleshooting
logging:
  level:
    org.hibernate.SQL: DEBUG
    com.zaxxer.hikari.HikariConfig: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE