spring:
  datasource:
    username: owner_service
    password: '{cipher}39a3618988ec8a5931f3da668627dda0a40dde6cea6a839cd585ea1819220535'
    url: jdbc:mysql://localhost:3306/ownerservice?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC

# Enable logging for config troubleshooting
logging:
  level:
    org.hibernate.SQL: DEBUG
    com.zaxxer.hikari.HikariConfig: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE